### ISSUE TITLE
(1.21) "Immediately Play" option and switching dimensions

### ISSUE THREAD

**Issue by mariberry-hearn** [PlasticStrawActivist/Infinite-music-mod#12]
Seems like there's a bug where switching dimensions with this option enabled causes the game to pull from the generic `music.game` sound event instead of choosing the appropriate biome. Causes a bit of tonal disconnect since it makes the Nether play the more light-hearted Overworld tracks

**Comment by PlasticStrawActivist** [comment]
Thanks I fixed this in the latest version
