### ISSUE TITLE
Crash on Client Start [Fabric 1.21.1 on 0.16.9]

### ISSUE THREAD

**Issue by suerion** [PlasticStrawActivist/Infinite-music-mod#15]
Hey, i got an crash on Startup from Client.

https://mclo.gs/ajyT9bJ

latest.log
https://mclo.gs/xIrFjZ4#L3808

**Comment by suerion** [comment]
@PlasticStrawActivist did you see the issue?

**Comment by iMoobert** [comment]
they don't seem to be active, they haven't replied to the issue some guy put in more than a month ago

**Comment by PlasticStrawActivist** [comment]
thanks for reporting
this should be fixed now
