### ISSUE TITLE
Crash on opening mod menu

### ISSUE THREAD

**Issue by freddycansic** [PlasticStrawActivist/Infinite-music-mod#2]
When I click on the mod in my mod menu to open the options, my game crashes.

[Here's the crash report](https://pastebin.com/DLDQN6Wb)  from Prism launcher.

I am using this mod along with the Fabulously Optimised modpack.

```
java.lang.NoSuchMethodError: 'void net.minecraft.class_353.<init>(net.minecraft.class_310, int, int, int, int, int)'
	at dev.plasticstraw.inf_music.screen.AbstractOptionsScreen.method_25426(AbstractOptionsScreen.java:26)
```
This is the error relating to this mod.

Thanks

**Comment by PlasticStrawActivist** [comment]
Thanks for reporting I fixed this in the [latest version](https://modrinth.com/mod/infinite-music/version/0.3.1)
