### ISSUE TITLE
Feature Request: Make music play when logging into a world

### ISSUE THREAD

**Issue by VeggeieDude** [PlasticStrawActivist/Infinite-music-mod#3]
Heya! I'd like to request a feature if that's okay. I noticed the music doesn't play until the delay time is first passed, but in vanilla it'll usually play when you log in to a world. Is it possible to add this as a feature? I have my music timer on 10 minute gaps, so for the first ten minutes there's no music haha

**Comment by PlasticStrawActivist** [comment]
Thanks for the suggestion. I added this in the latest version.

**Comment by VeggeieDude** [comment]
Awesome ty! May I make one more request XD, if you can backport it to 1.20.1 lol. If not no worries!
