### ISSUE TITLE
Overworld music plays in Nether dimension

### ISSUE THREAD

**Issue by GalaxyNation** [PlasticStrawActivist/Infinite-music-mod#4]
When you enter the Nether, the first song that plays is a song from the overworld. But all the music thereafter is Nether music. I know this is a very small issue that doesn't make much of a difference but I would still like to see this fixed. Overall I do think the mod is quite great. Thanks for your effort in the mod and thanks for your time reading this.

**Comment by PlasticStrawActivist** [comment]
This was caused by a MC bug. Changes in 1.20.5 have fixed this bug and this no longer happens.

**Comment by GalaxyNation** [comment]
Yeah I recently saw the mod was updated for 1.20.6 and the mod works perfectly now. Absolutely amazing mod you've made, thank you so much!
