### ISSUE TITLE
[1.21] Infinite Music Options visual bug.

### ISSUE THREAD

**Issue by Soufre** [PlasticStrawActivist/Infinite-music-mod#7]
The options screen stacks every time the preset is changed, it then resets when the tab closes.

https://github.com/PlasticStrawActivist/Infinite-music-mod/assets/96512010/b73d52ed-f0d1-4205-8a39-2bd4864a2113

**Comment by PlasticStrawActivist** [comment]
Thanks for reporting, fixed in the latest version
